### ISSUE TITLE
Lzma library error:  No progress is possible)

### ISSUE THREAD

**Issue by gmicroul** [devops117/kupferbootstrap#1]
Optional dependencies for mkinitcpio-kupfer
    xz: Use lzma or xz compression for the initramfs image [installed]
    bzip2: Use bzip2 compression for the initramfs image [installed]
    lzop: Use lzo compression for the initramfs image
    lz4: Use lz4 compression for the initramfs image [installed]
    mkinitcpio-nfs-utils: Support for root filesystem on NFS
( 96/632) installing linux-sdm845                                   [######################################] 100%
error: could not extract /home/user/.cache/kupfer/chroots/rootfs_sdm845-oneplus-fajita-phosh/usr/lib/modules/6.11.0-sdm845/kernel/drivers/bus/mhi/host/mhi.ko.zst (Lzma library error:  No progress is possible)
error: problem occurred while installing linux-sdm845
Optional dependencies for linux-sdm845
    crda: to set the correct wireless channels of your country [pending]
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
2024-12-06 10:06:10 CRITICAL: 
Traceback (most recent call last):
  File "/home/user/kupferbootstrap/main.py", line 59, in main
    return cli(prog_name='kupferbootstrap')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[...]
  File "/home/user/kupferbootstrap/chroot/base.py", line 50, in create_rootfs
    raise Exception(f'Failed to initialize chroot "{self.name}"')
Exception: Failed to initialize chroot "rootfs_sdm845-oneplus-fajita-phosh"

**Comment by devops117** [comment]
Hi, this isn't official kupferbootstrap repo or maintained otherwise

please use the official repo at: https://gitlab.com/kupfer/kupferbootstrap
